### ISSUE TITLE
Enumeration Failed 

### ISSUE THREAD

**Issue by tlarocca282** [pfred/pfred.github.com#1]
Hi, using PFRED for first time on MacOS 11.4, java (build 1.8.0_321-b07).  

Having problem with bringing in Ensemble gene ID.  When i input and particular ENSG and attempt to retrieve ortholog sequence, no primary or secondary targets are identified and subsequently receive "Enumeration Failed" message.  

Also, when I click the ensembl button to retrieve other IDs, it does not bring me to ensembl website

Help would be greatly appreciated!

**Comment by TianhongZhang** [comment]
How did you run the client? From source code or from the released jars?
Did you setup your own service or use the public one from https://os.biogen.com?
If I download the released jars and run it as it using the default service, I can run through ASO design with the default Ensemble ID.

**Comment by tlarocca282** [comment]
Thanks for the reply

I went to pfred.github.io
   Launch pfred -> downloaded the .jlnp file

https://os.biogen.com<https://os.biogen.com/> doesn't work on my end


_______________________________

Thomas J. LaRocca, MD, PhD
Clinical Assistant Professor
Pediatric Critical Care Medicine
Lucile Packard Children's Hospital
Stanford University School of Medicine
770 Welch Road Suite 435
Palo Alto, CA 94304


________________________________

**Comment by TianhongZhang** [comment]
can you download the zip file from here and give it a try? The JNLP file is not supported anymore.
https://github.com/pfred/pfred-gui/releases/tag/v1.0

**Comment by tlarocca282** [comment]
Hi Tianhong
I tried opening but Java failed to open.  I have downloaded the latest version of java.
Any other assist?
Thank you so much for helping


_______________________________

Thomas J. LaRocca, MD, PhD
Clinical Assistant Professor
Pediatric Critical Care Medicine
Lucile Packard Children's Hospital
Stanford University School of Medicine
770 Welch Road Suite 435
Palo Alto, CA 94304


________________________________

**Comment by TianhongZhang** [comment]
hmm, can you describe your environment (OS, Java version) and the steps you took and any error messages? 
Thanks
Tianhong

**Comment by tlarocca282** [comment]
Hi Tian
I am using MacOsX 11.4 and using java v8 update 321
When I open the jar file from the zip you recommended, I receive java error message:  Java application launch failed
Thanks for helping, really would be great to get this to work...



________________________________

**Comment by TianhongZhang** [comment]
Sorry that I need more details. How did you run the jar file? Did you try to double click on it or run it from command line like below?
java -jar $PATHTOPFRED-GUI/PFRED-1.0.jar

**Comment by tlarocca282** [comment]
Thanks for the quick repsonse
I have tried both,
When I double click, I receive the java error message, Java application launch failed

When I open the terminal I also receive error message below:


***@***.*** ~ % java -jar $PATHTOPFRED-GUI/PFRED-1.0.jar

Unrecognized option: -GUI/PFRED-1.0.jar

Error: Could not create the Java Virtual Machine.

Error: A fatal exception has occurred. Program will exit.


I am not familiar with using terminal language.  Learning as I go.  Thank you for your help!!


_______________________________

Thomas J. LaRocca, MD, PhD
Clinical Assistant Professor
Pediatric Critical Care Medicine
Lucile Packard Children's Hospital
Stanford University School of Medicine
770 Welch Road Suite 435
Palo Alto, CA 94304


________________________________

**Comment by TianhongZhang** [comment]
Sorry that I didn't realize you are not familiar with Java and using Terminal on your Mac. I am providing more detailed steps for you to follow:

1. Download the PFRED-1.0.zip file from github to your machine and put it in your Downloads folder in your home directory
2. Unzip this file in the Downloads folder and you will see a new folder with the name of PFRED-1.0, the PFRED-1.0.jar file will be in this new folder
3. Open your Terminal and type in 'java -version' to show which java will be used. Should be Java 1.8 or higher. You are in your home directory now
4. change to the program folder with the following command in your Terminal:  'cd Downloads/PFRED-1.0'
5.  type in 'java -jar PFRED-1.0.jar' to launch PFRED
6. Note: remove the quote from the commands above and hit return to execute them.
7. Good Luck!

**Comment by tlarocca282** [comment]
Tian
Thank you! Worked!  Will def reach out if I have further questions.  Thank you again, and looking forward to using this valuable resource!
All the best
Tom

_______________________________

Thomas J. LaRocca, MD, PhD
Clinical Assistant Professor
Pediatric Critical Care Medicine
Lucile Packard Children's Hospital
Stanford University School of Medicine
770 Welch Road Suite 435
Palo Alto, CA 94304


________________________________
